server:
  port: 8202

spring:
  application:
    name: service-cmn
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/appointment?characterEncoding=utf-8&useSSL=false&serverTimezone=GMT
    username: root
    password: root
  # 返回json的全局时间格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

mybatis-plus:
  # mapper文件地址
  mapper-locations: classpath:com/terminus/cmn/mapper/*.xml

## nacos服务地址
#spring.cloud.nacos.discovery.server-addr=127.0.0.1:8848
#
##开启sentinel
#feign.sentinel.enabled=true
##设置sentinel地址
#spring.cloud.sentinel.transport.dashboard=http://127.0.0.1:8858
#
##mongodb地址
#spring.data.mongodb.host=192.168.44.163
#spring.data.mongodb.port=27017
#spring.data.mongodb.database=yygh_hosp
#
##rabbitmq地址
#spring.rabbitmq.host=127.0.0.1
#spring.rabbitmq.port=5672
#spring.rabbitmq.username=guest
#spring.rabbitmq.password=guest

