server:
  port: 8201

spring:
  application:
    name: service-hospital
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/appointment?characterEncoding=utf-8&useSSL=false&serverTimezone=GMT
    username: root
    password: root
  # 返回json的全局时间格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  data:
    mongodb:
      uri: mongodb://localhost:27017/appointment_hospital

mybatis-plus:
  # mapper文件地址
  mapper-locations: classpath:com/terminus/hospital/mapper/*.xml

## nacos服务地址
#spring.cloud.nacos.discovery.server-addr=127.0.0.1:8848
#
##开启sentinel
#feign.sentinel.enabled=true
##设置sentinel地址
#spring.cloud.sentinel.transport.dashboard=http://127.0.0.1:8858
#
##mongodb地址

#
##rabbitmq地址
#spring.rabbitmq.host=127.0.0.1
#spring.rabbitmq.port=5672
#spring.rabbitmq.username=guest
#spring.rabbitmq.password=guest

