server:
  port: 8204

spring:
  application:
    name: service-sms
    # 返回json的全局时间格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  redis:
    host: localhost
    port: 6379
    database: 0
    timeout: 180000
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
